import { FileText, Calendar, ChevronRight } from "lucide-react";
import type { ReportSpec } from "@/types";
import { cn, formatDate } from "@/lib/utils";
import { ReportSection } from "./ReportSection";

/* ------------------------------------------------------------------ */
/*  ReportViewer – full report preview with title page and TOC         */
/* ------------------------------------------------------------------ */

interface ReportViewerProps {
  report: ReportSpec;
  className?: string;
}

function formatReportType(reportType: string): string {
  return reportType
    .replace(/_/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function getReportTypeColor(reportType: string): string {
  const lower = reportType.toLowerCase();
  if (lower.includes("board") || lower.includes("executive"))
    return "badge-chief";
  if (lower.includes("project") || lower.includes("sprint"))
    return "badge-teal";
  if (lower.includes("risk")) return "badge-warm";
  if (lower.includes("team") || lower.includes("resource"))
    return "badge-neutral";
  return "badge-teal";
}

export function ReportViewer({ report, className }: ReportViewerProps) {
  const sortedSections = [...report.sections].sort(
    (a, b) => a.order - b.order,
  );

  const scrollToSection = (sectionId: string) => {
    const el = document.getElementById(`section-${sectionId}`);
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  return (
    <div className={cn("space-y-8", className)}>
      {/* Title page */}
      <div className="card overflow-hidden">
        <div className="bg-gradient-to-br from-teal-500 to-chief-600 px-8 py-10 text-white">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/20">
              <FileText className="h-5 w-5" />
            </div>
            <span className={getReportTypeColor(String(report.report_type))}>
              {formatReportType(String(report.report_type))}
            </span>
          </div>

          <h1 className="mt-5 text-2xl font-bold leading-tight">
            {report.title}
          </h1>

          <div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-teal-100">
            <div className="flex items-center gap-1.5">
              <Calendar className="h-4 w-4" />
              <span>{formatDate(report.created_at, "MMMM d, yyyy")}</span>
            </div>
            {report.time_scope && Object.keys(report.time_scope).length > 0 && (
              <span className="rounded-full bg-white/10 px-3 py-0.5 text-xs">
                {Object.values(report.time_scope).join(" - ")}
              </span>
            )}
          </div>

          {/* Branding */}
          <div className="mt-6 flex items-center gap-2 border-t border-white/20 pt-4">
            <div className="flex h-6 w-6 items-center justify-center rounded bg-white/20 text-xs font-bold">
              CO
            </div>
            <span className="text-xs text-teal-100">
              Generated by ChiefOps AI
            </span>
          </div>
        </div>
      </div>

      {/* Table of contents */}
      {sortedSections.length > 1 && (
        <div className="card">
          <h2 className="mb-3 text-sm font-semibold text-slate-900 dark:text-white">
            Table of Contents
          </h2>
          <nav className="space-y-1">
            {sortedSections.map((section, idx) => (
              <button
                key={section.section_id}
                onClick={() => scrollToSection(section.section_id)}
                className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm text-slate-600 transition-colors hover:bg-slate-50 hover:text-teal-700 dark:text-slate-400 dark:hover:bg-slate-800 dark:hover:text-teal-400"
              >
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded bg-slate-100 text-2xs font-medium text-slate-500 dark:bg-slate-700 dark:text-slate-400">
                  {idx + 1}
                </span>
                <span className="flex-1 truncate">{section.title}</span>
                <ChevronRight className="h-3.5 w-3.5 shrink-0 text-slate-300 dark:text-slate-600" />
              </button>
            ))}
          </nav>
        </div>
      )}

      {/* Report sections */}
      {sortedSections.map((section, idx) => (
        <div key={section.section_id}>
          {/* Page break indicator */}
          {idx > 0 && (
            <div className="my-6 flex items-center gap-3">
              <div className="h-px flex-1 bg-slate-200 dark:bg-slate-700" />
              <span className="text-2xs font-medium uppercase tracking-wider text-slate-400 dark:text-slate-500">
                Section {idx + 1}
              </span>
              <div className="h-px flex-1 bg-slate-200 dark:bg-slate-700" />
            </div>
          )}

          <div className="card">
            <ReportSection section={section} />
          </div>
        </div>
      ))}
    </div>
  );
}
